### ISSUE TITLE
feat(plugin-cicd-github): consider infra/lambdas changes for CI/CD pipeline

### ISSUE THREAD

**Issue by flozonn** [genjsdev/genjs#11]
related file : https://github.com/genstackio/genjs/blob/master/packages/plugin-cicd-github/templates/workflows/parallel-pull-request-to-env-infra.yml.ejs
(genjs/packages/plugin-cicd-github/templates/workflows/parallel-pull-request-to-env-infra.yml.ejs)

During the layer LAMBDA @ edge deployment, the changes in file  infra/lambdas/webhooks.js are not considered.
Therefore the init-plan-apply of the layer of type "genstackio/layer-webhooks/aws" does not occur when merging a PR.

Can we add the file `infra/lambdas/webhooks.js` to the generate list in `.github/workflows/parallel-deploy-to-env-infra.yml`

**Comment by ohoareau** [comment]
Thanks for your proposal. You are right, currently this is a limitation, we cannot add extra path to take into account for detecting changes for jobs/layers. I can add a new feature to optionally add extra paths from inside the yml configuration file.
I'll try to work on that this week.

**Comment by ohoareau** [comment]
This issue should be fixed in #12, `infra/lambdas/<layer-name>.js` and `infra/functions/<layer-name>.js` are now automatically added in the list of tracked paths. Additionally, it is now possible to specify extra custom paths in the `scmTrackedPaths` optional property of layer in the `.genjs/projects/infra.yml` file. This new optional property, if present, must be an array of strings, these strings will be appended to the list of tracked paths for the job.

**Comment by ohoareau** [comment]
New feature available in `@genjs/genjs-plugin-cicd-github@0.6.8`
